// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEG4rF2bSxe-wnHxOOctj2lfblEWcMGSU',
    appId: '1:697967767815:web:f5acd6366b729beba655a2',
    messagingSenderId: '697967767815',
    projectId: 'currensee-4f4cc',
    authDomain: 'currensee-4f4cc.firebaseapp.com',
    storageBucket: 'currensee-4f4cc.appspot.com',
    measurementId: 'G-3P61QWPQG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8WuiOv1-YF_2kXXKytYoRCCivxMuT1vI',
    appId: '1:697967767815:android:ae936457cc606c66a655a2',
    messagingSenderId: '697967767815',
    projectId: 'currensee-4f4cc',
    storageBucket: 'currensee-4f4cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl531Q0rAR9pfO0qjqL7gUpwrYEHn-KVo',
    appId: '1:697967767815:ios:177f21cc3c510627a655a2',
    messagingSenderId: '697967767815',
    projectId: 'currensee-4f4cc',
    storageBucket: 'currensee-4f4cc.appspot.com',
    iosBundleId: 'com.example.currenSee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl531Q0rAR9pfO0qjqL7gUpwrYEHn-KVo',
    appId: '1:697967767815:ios:a1ffbbb8b0e8221aa655a2',
    messagingSenderId: '697967767815',
    projectId: 'currensee-4f4cc',
    storageBucket: 'currensee-4f4cc.appspot.com',
    iosBundleId: 'com.example.currenSee.RunnerTests',
  );
}
